name:                melange
version:             0.1.0.0
github:              "githubuser/melange"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2018 Author name here"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/melange#readme>

dependencies:
- base >= 4.7 && < 5
- aeson
- blaze-html
- bytestring
- containers
- generics-sop
- mtl
- monad-control
- http-media
- postgresql-simple
- safe-exceptions
- servant
- servant-server
- squeal-postgresql
- text
- time
- transformers-base
- uuid
- wai
- wai-cors
- wai-extra
- warp

library:
  source-dirs: src
  ghc-options:
    - -Wall


executables:
  migrate:
    main:                Migrate.hs
    source-dirs:         app/Migrate
    ghc-options:
    - -main-is Migrate
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - melange

  server:
    main:                Server.hs
    source-dirs:         app/Server
    ghc-options:
    - -main-is Server
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - melange

tests:
  melange-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -main-is Spec
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - melange
    - hspec
    - string-qq
    - time
    - uuid
